--- build/config/BUILD.gn.orig	2025-01-01 00:00:00 UTC
+++ build/config/BUILD.gn
@@ -210,11 +210,17 @@
     # linking can have run-time side effects, nothing should be listed here.
     libs = []
   } else if (is_linux || is_chromeos) {
-    libs = [
-      "dl",
-      "pthread",
-      "rt",
-    ]
+    if (current_os == "freebsd") {
+      libs = [
+        "pthread",
+      ]
+    } else {
+      libs = [
+        "dl",
+        "pthread",
+        "rt",
+      ]
+    }
   }
 }
